version: '3'

services:
  gitness:
    image: harness/gitness
    container_name: gitness
    restart: always
    ports:
      - "${HOST_PORT}:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/gitness:/data
    networks:
      - gitness_network

networks:
  gitness_network:
    driver: bridge
